SELECT * FROM EMP;

SELECT EMPNO, ENAME, SAL FROM EMP;		-- 사원번호, 사원이름, 월급 조회

SELECT ENAME AS "이름", SAL "월급" FROM EMP;		--큰따옴표는 식별자

/*사원번호, 사원이름, 월급, 연봉을 조회하고.. 컬럼명은 사원번호, 사원이름, 월급, 연봉으로 출력*/

SELECT EMPNO "사원이름", ENAME "사원이름", SAL "월급", SAL*12 "연봉" FROM EMP;

SELECT DISTINCT JOB FROM EMP;			-- DISTINCT: 중복제거
SELECT DISTINCT JOB, DEPTNO FROM EMP;
SELECT ALL JOB, DEPTNO FROM EMP;		-- ALL: 중복에 상관없이 모두 출력

SELECT 'ABC' FROM DUAL;
SELECT 2 + 3 FROM DUAL;
SELECT 'ABC', 2 + 3 FROM DUAL;
SELECT 2 + 3 AS RESULT FROM DUAL;
SELECT 1 + '5' FROM DUAL;
SELECT '1' + '5' FROM DUAL;		-- 15라는 값을 뽑으려면..
--SELECT "1" + "5" FROM DUAL;
SELECT  1||'5' FROM DUAL;

/* 사원명과 업무로 연결(SMITH, CLERK) 표시하고 컬럼명은 EMPLOYEE AND JOB으로 표시 */

SELECT '(' ||ENAME|| ',' ||JOB|| ')' AS "Employee and Job" FROM EMP;		-- 문자열 붙히기

/* 사원별 연간 총 수입을 조회하시오.(별칭: 연간총수입)*/
SELECT * FROM EMP;
SELECT ENAME, SAL*12 FROM EMP;
SELECT ENAME, (SAL*12)+ NVL(COMM, 0) "연간 총 수입" FROM EMP;		-- 보너스까지 더해서 총 수익

SELECT * FROM EMP ORDER BY SAL;
SELECT * FROM EMP ORDER BY EMPNO;
SELECT * FROM EMP ORDER BY SAL DESC;

-- 조건을 추가하는 WHERE절
SELECT * FROM EMP WHERE EMPNO = 7839;

-- 사원번호가 7689번인 사원이름과 업무, 급여를 출력하시오
SELECT * FROM EMP;
SELECT ENAME, JOB, SAL FROM EMP WHERE EMPNO = 7698;

-- SMITH의 이름, 월급, 업무 출력
SELECT * FROM EMP WHERE ENAME = 'SMITH';

SELECT * FROM EMP WHERE SAL = 3000;
SELECT * FROM EMP WHERE SAL != 3000;
SELECT * FROM EMP WHERE SAL ^= 4000;
SELECT * FROM EMP WHERE SAL <> 5000;
SELECT * FROM EMP WHERE NOT SAL = 6000;		-- !=, ^=, <>(ANSII), NOT: ~이 아닌(논리 부정)으로 사용
SELECT * FROM EMP WHERE ENAME >= 'M';		-- 첫 글자가 'M'이거나 M보다 큰 문자열 출력

-- 월급이 2500이상이고 3000미만인 사원과 입사일, 월급을 출력
SELECT ENAME, HIREDATE, SAL FROM EMP WHERE 2500 <= SAL AND SAL < 3000;

-- 월급이 2000이상이고 3000이하에 포함되지 않는 사원이름과 월급, 입사일을 조회
SELECT ENAME, HIREDATE, SAL FROM EMP WHERE NOT 2000 <= SAL AND 3000 >= SAL;
SELECT * FROM EMP WHERE SAL BETWEEN 2500 AND 3000;

-- 월급이 2000이상이고 3000이하에 포함되지 않는 사원의 이름과 월급, 입사일을 조회하시오.
-- 81년 5월 1일과 동년 12월 3일 사이에 입사한 사원의 이름, 월급, 입사일을 조회하시오. 날짜 포맷
SELECT ENAME, SAL, HIREDATE FROM EMP WHERE HIREDATE BETWEEN TO_DATE('19810501', 'YYYYMMDD') AND TO_DATE('19811203', 'YYYYMMDD');
--SELECT ENAME, SAL , HIREDATE FROM EMP e WHERE HIREDATE BETWEEN '81-5-1' AND '81-12-3';

-- 1987년도 입사한 사원명, 월급, 입사일 출력
SELECT ENAME, SAL, HIREDATE FROM EMP WHERE HIREDATE BETWEEN TO_DATE('19870101', 'YYYYMMDD') AND TO_DATE('19871231', 'YYYYMMDD');

-- 직업이 'MANAGER', 'CLERK', 'SALESMAN'인 사람을 출력
SELECT * FROM EMP;
SELECT * FROM EMP WHERE JOB = 'MANAGER' OR JOB ='CLERK' OR JOB = 'SALESMAN';
SELECT * FROM EMP WHERE JOB IN ('MANAGER', 'SALESMAN');

-- 사번이 7566, 7782, 7934인 사원을 제외한 사람의 사번, 이름, 월급을 출력
SELECT EMPNO, ENAME, SAL FROM EMP WHERE EMPNO NOT IN (7566, 7782, 7934);

-- 부서번호 30에서 근무하고 월 2000달러 이하를 받는 81년 5월 1일 이전에 입사한 사원의 이름, 월급, 부서번호, 입사일 조회
SELECT * FROM EMP;
SELECT ENAME, SAL, DEPTNO, HIREDATE FROM EMP WHERE DEPTNO IN'30' AND SAL <= 2000 AND HIREDATE <= '19810501';

-- 부서번호가 10 또는 30인 부서에서 2000 이상 5000이하의 사원명, 급여 부서번호 조회
SELECT ENAME, SAL, DEPTNO FROM EMP WHERE DEPTNO IN ('10', '30') AND SAL BETWEEN 2000 AND 5000;

-- JOB이 MANAGER OR SALESMAN 급여 1600, 2975, 2850가 아닌 사원명, 입사일, 급여, 부서번호 출력
SELECT ENAME, HIREDATE, SAL, DEPTNO FROM EMP WHERE JOB IN ('MANAGER', 'SALESMAN') AND SAL NOT IN (1600, 2975, 2850);

SELECT * FROM EMP WHERE ENAME LIKE 'S%';		-- 첫 글자가 'S'인 문자열 출력
-- %: 와일드카드, 대표표기(여기서는 나머지 문자열을 대신하여 사용 됨)
SELECT * FROM EMP WHERE ENAME LIKE '_L%';		-- 두번째 글자가 'L'인 문자열 출력

-- 사원 이름 중 'S'가 포함되지 않는 부서번호 20인 사원의 이름, 부서번호 조회
SELECT ENAME, DEPTNO FROM EMP WHERE DEPTNO = '20' AND ENAME NOT LIKE '%S%';

-- 19810601 ~ 19811231 입사자 중 부서명이 30인 사원의 부서번호, 사원명, 직업, 입사일 출력(입사일 오름차순 정렬)
SELECT DEPTNO, ENAME, JOB, HIREDATE 
FROM EMP 
WHERE DEPTNO = '30' AND HIREDATE BETWEEN '19810601' AND '19811231'
ORDER BY HIREDATE;



