/* DDL */
-- 테이블 생성
CREATE TABLE EMP_DDL(
	EMPNO		NUMBER(4),		-- 열이름	자료형()
	ENAME		VARCHAR2(10),
	JOB			VARCHAR2(9),
	MGR			NUMBER(4),
	HIREDATE	DATE,
	SAL			NUMBER(7, 2),
	COMM		NUMBER(7, 2),
	DEPTNO		NUMBER(2)
);
CREATE TABLE EMP_DDL1 AS SELECT * FROM EMP WHERE DEPTNO = 30;
SELECT * FROM EMP_DDL1;
CREATE TABLE EMP_DDL2 AS SELECT * FROM EMP WHERE 1 <> 1;
SELECT * FROM EMP_DDL2;

-- 테이블 수정
ALTER TABLE EMP_DDL1 ADD HP VARCHAR2(20);			-- 열 추가
SELECT * FROM EMP_DDL1;
ALTER TABLE EMP_DDL1 RENAME COLUMN HP TO TEL;		-- 컬럼명 변경
COMMIT;

ALTER TABLE EMP_DDL1 MODIFY EMPNO NUMBER(10);
ALTER TABLE EMP_DDL1 DROP COLUMN TEL;
TRUNCATE TABLE EMP_DDL1;					-- 전체 데이터 삭제
DROP TABLE EMP_DDL1;
DROP TABLE EMP_DDL2;
DROP TABLE EMP_DDL;

/* 제약조건 */
CREATE TABLE TBL_EX (
	LOGIN_ID VARCHAR2(20) NOT NULL,
	LOGIN_PW VARCHAR2(20) NOT NULL,
	TEL		 VARCHAR2(20)
);
SELECT * FROM TBL_EX;
INSERT INTO TBL_EX (LOGIN_ID, LOGIN_PW, TEL)
VALUES ('AAAA', '1234', NULL);
INSERT INTO TBL_EX (LOGIN_ID, LOGIN_PW, TEL)
VALUES ('BBBB', 'NULL', NULL);		-- 비밀번호가 'NULL'문자열임
--ALTER TABLE TBL_EX MODIFY TEL NOT NULL;		-- 이미 기존 테이블에 NULL값이 존재하기 때문에 오류.
UPDATE TBL_EX SET TEL = '010-1234-5678' WHERE LOGIN_ID = 'AAAA';

-- UNIQUE
CREATE TABLE TBL_UNIQ2 (
	LOGIN_ID VARCHAR (20) PRIMARY KEY,	-- 중복과 NULL을 허용하지 않는다.
	LOGIN_PW VARCHAR (20) NOT NULL,
	TEL 	 VARCHAR (20)
);
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME FROM USER_CONSTRAINTS;

SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME, R_OWNER, R_CONSTRAINT_NAME
FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN ('EMP', 'DEPT');

-- CHECK
-- 010-[1-5][0-9][0-9][0-9]-[0-9][0-9][0-9][0-9]
-- 010-\d\d\d\d-\d\d\d\d
-- ^010-\d{4}-\d{4}$
CREATE TABLE TBL_CHK (
	LOGIN_ID VARCHAR2(20) CONSTRAINT TBLCK_LOGINID_PK PRIMARY KEY,
	LOGIN_PW VARCHAR2(20) CONSTRAINT TBLCK_LOGINPW_CK CHECK (LENGTH(LOGIN_PW) > 3),
	TEL 	 VARCHAR(20)
);

-- 1. EMP 테이블에서 사원번호가 7521인 사원의 직업과 같고, 
-- 	  사원번호 7934인 사원의 급여보다 많은 사원의 사번, 이름, 직업, 급여를 출력

SELECT * FROM EMP;
SELECT EMPNO, ENAME, JOB, SAL
FROM EMP
WHERE SAL > (SELECT SAL FROM EMP WHERE EMPNO = 7934)
AND JOB = (SELECT JOB FROM EMP WHERE EMPNO = 7521);


-- 2. 직업별로 최소 급여를 받는 사원의 정보를 사원번호, 이름, 업무, 부서명으로 출력(직업별 내림차순)

SELECT EMPNO, ENAME, JOB, DNAME
FROM EMP E LEFT OUTER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
--FROM EMP NATURAL JOIN DEPT
--FROM EMP E INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
WHERE (JOB, SAL) IN (SELECT JOB, MIN(SAL) FROM EMP GROUP BY JOB)
ORDER BY JOB DESC;


-- 3. 각 사원별 커미션이 0또는 NULL이고 부서위치가 'GO'로 끝나는 사원의 정보를 
-- 	  사원번호, 이름, 커미션, 부서번호, 부서명, 지역을 출력(보너스가 NULL이면 0으로 출력)

SELECT EMPNO, ENAME, NVL(COMM, 0), DEPTNO, DNAME, LOC		
-- NVL(값1, 값2) 값1이 NULL이면 값2로 출력.
FROM EMP NATURAL JOIN DEPT
WHERE (COMM= 0 OR COMM IS NULL)AND LOC LIKE '%GO';








