CREATE TABLE DEPT_tmp AS SELECT * FROM DEPT d ;
SELECT * FROM DEPT_TMP;

-- UPDATE _ SET
UPDATE DEPT_TMP SET LOC = 'SEOUL';			-- 해당열 전체 수정
UPDATE DEPT_TMP SET DNAME = 'DATABASE', LOC = 'PUSAN'
WHERE DEPTNO = 40;

-- 서브쿼리를 사용한 데이터 수정
UPDATE DEPT_TMP SET (DNAME, LOC) = (SELECT DNAME, LOC FROM DEPT WHERE DEPTNO = 40)
WHERE DEPTNO = 40;

-- DELETE
CREATE TABLE EMP_TMP AS SELECT * FROM EMP;
SELECT * FROM EMP_TMP;
DELETE FROM EMP_TMP WHERE JOB = 'SALESMAN';

-- 서브쿼리 삭제
DELETE FROM EMP_TMP;			--DATA를 삭제
SELECT * FROM EMP_TMP;
DROP TABLE EMP_TMP;				-- 테이블 삭제(DROP TABLE [테이블 이름])

-- 트렌젝션
CREATE TABLE CEPT_TMP AS
SELECT * FROM TAB;
SELECT * FROM DEPT_TMP;
CREATE TABLE DEPT_TCL AS SELECT * FROM DEPT;
SELECT * FROM DEPT_TCL;

INSERT INTO DEPT_TCL VALUES(50, 'DATABASE', 'BUSAN');
UPDATE DEPT_TCL SET LOC = 'BUSAN' WHERE DEPTNO = 40;
DELETE FROM DEPT_TCL WHERE DNAME = 'RESEARCH';
-- 트랜잭션이 실행중일때는 LOCK이 걸림
ROLLBACK;				-- 트랜잭션 취소
COMMIT;					-- 트랜잭션 반영
DROP TABLE DEPT_TCL;

-- VIEW 하나이상의 쿼리를 가지고 있는..
CREATE VIEW VM_EMP AS (SELECT EMPNO, ENAME, JOB, DEPTNO FROM EMP WHERE DEPTNO = 20);
SELECT * FROM VM_EMP;
SELECT * FROM USER_VIEWS;		-- 내가 만든 뷰
DROP VIEW VM_EMP;

-- 테이블, 데이터사전, 인덱스, 뷰, 시퀀스, 동의어
-- 데이터 사전
SELECT * FROM DICT;			-- 사용 가능한 데이터 사전
SELECT TABLE_NAME FROM USER_TABLES;			-- 현재 접속사용자(ADAM)이 가지고 있는 테이블 조회 
SELECT OWNER, TABLE_NAME FROM ALL_TABLES;	-- 현재 계정이 접속 가능한 모든 테이블 조회
SELECT * FROM DBA_TABLES;					-- 관리 권한의 사용자만 접근 가능

-- 시퀀스
CREATE TABLE DEPT_SEQ AS SELECT * FROM DEPT WHERE 1 <> 1;
SELECT * FROM DEPT_SEQ;
DROP TABLE DEPT_SEQ;

CREATE SEQUENCE SEQ_DEPT_SEQUENCE			-- 시퀀스 테이블 이름
INCREMENT BY 10								-- 증가하는 값
START WITH 10								-- 시작 값
MAXVALUE 90									-- 최대 값
MINVALUE 0									-- 최소 값
NOCYCLE										-- 최대값이면 정지 / 순환하지 않음.
CACHE 2;									-- 2개의 캐시를 사용

SELECT * FROM USER_SEQUENCES;
-- 시퀀스이름 NEXTVAL
INSERT INTO DEPT_SEQ (DEPTNO, DNAME, LOC)
VALUES (SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE', 'BUSAN');
	SELECT * FROM DEPT_SEQ ORDER BY DEPTNO;

INSERT INTO DEPT_SEQ (DEPTNO, DNAME, LOC)
VALUES (SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE1', 'SEOUL');
	SELECT * FROM DEPT_SEQ ORDER BY DEPTNO;

INSERT INTO DEPT_SEQ (DEPTNO, DNAME, LOC)
VALUES (SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE2', 'SEOUL');
	SELECT * FROM DEPT_SEQ ORDER BY DEPTNO;

SELECT SEQ_DEPT_SEQUENCE.CURRVAL FROM DUAL;

-- 시퀀스 수정
ALTER SEQUENCE SEQ_DEPT_SEQUENCE INCREMENT BY 3 MAXVALUE 99 CYCLE;
SELECT * FROM USER_SEQUENCES;
DROP SEQUENCE SEQ_DEPT_SEQUENCE;



